export default [
  { id: "banana" },
  { id: "bean" },
  { id: "beer" },
  { id: "carrot" },
  { id: "cherries" },
  { id: "chicken" },
  { id: "chocolate" },
  { id: "coconut" },
  { id: "crab" },
  { id: "egg" },
  { id: "fish" },
  { id: "flour" },
  { id: "gelatin" },
  { id: "grapes" },
  { id: "jalapeno" },
  { id: "meal" },
  { id: "milk" },
  { id: "mushroom" },
  { id: "pepper" },
  { id: "pineapple" },
  { id: "redwine" },
  { id: "salt" },
  { id: "squid" },
  { id: "sugar" },
  { id: "whitewine" }
];
